### ISSUE TITLE
The plugin seems to fail with NativeScript 2.1.1

### ISSUE THREAD

**Issue by giordy** [rborn/nativescript-i18n#10]
Hi,

I tried today your plugin and I think it creates a small conflict with NativeScript 2.1.1.
In fact after integrating it in the project and adding one simple string to test it I experienced this error:

```
:processF0F1DebugResources/home/gio/GIT/inline/platforms/android/build/intermediates/manifests/full/F0F1/debug/AndroidManifest.xml:31:28-57 : AAPT: No resource found that matches the given name (at 'label' with value '@string/title_activity_kimera').
```

Basically the plugin is overwriting the strings.xml files for the Android platform and removing one string that is referenced from the Android Manifest, namely: **title_activity_kimera**.

Thanks

P.S. as a workaround I'm including the strings that are being generated by the tool in the i18n strings.xml files, however it would be nice to solve the problem in the plugin or at least instruct the users in the documentation

**Comment by rborn** [comment]
Hi @giordy 
Are you by any chance using livesync? 

Also, the [Readme/important section](https://github.com/rborn/nativescript-i18n#important-) says that you should have that string in your xml lang files.
Anyway, if you have a better way of doing this I'm happy to accept a PR :)

**Comment by giordy** [comment]
aaaargh, somehow I missed that note! ^_^'
Sorry my bad!

I will consider the possibility of PR, in the meantime thanks a lot for your prompt reply and for your great work :)
