### ISSUE TITLE
Any way to set the default language?

### ISSUE THREAD

**Issue by magar91** [rborn/nativescript-i18n#11]
In my app I have two languages spanish and english but I want to make spanish the default language in case that the device has any other language. Is there any way to set a default language?

**Comment by rborn** [comment]
I'm not sure, I'll have to investigate :)

**Comment by ahmedelgendy** [comment]
+1

**Comment by lukashlobil** [comment]
I haven't investigated for iOS, but this is postinstall for Android. English is forced to be default language. 
```
if (lang === 'en') {
    outputFile = path.join(appResourcesDirectoryPath, 'Android', 'values', 'strings.xml');
} else {
    outputFile = path.join(appResourcesDirectoryPath, 'Android', 'values-' + lang, 'strings.xml');
}
```
Removing the if clause enables english not to default (there would be values-en). Then we'd need to read the default language string (ie. from package.json) and do the if clause for that language.

**Comment by rborn** [comment]
@lukashlobil yes, this is the approach I wanna take, only that I was very busy. Gimme few days to try to find some time to do this 😄

**Comment by rborn** [comment]
@lukashlobil actually if you look into https://github.com/rborn/nativescript-i18n/blob/custom_lang_path/lib/before-prepare.js#L12 I already did this for #28

**Comment by lukashlobil** [comment]
@rborn oh, cool! 
I forked it and implemented default language (settable in package.json) both [with custom location](https://github.com/lukashlobil/nativescript-i18n/blob/deafult_custom_lang/lib/before-prepare.js) and [without](https://github.com/lukashlobil/nativescript-i18n/blob/default_lang/lib/before-prepare.js) custom location. Looks good so far. I will do some tests, fix formatting and will do PR tomorrow . Let me know what you think if you can.

**Comment by rborn** [comment]
@lukashlobil looks good 😄 

if you want you can bump the version to 0.1.0 (as I think the module can be considered out of beta now), update the readme with the info about the defaultLang and I'll review the PR and push it to npm if all ok.

thanks again 👍
