### ISSUE TITLE
Getting errors during --watch

### ISSUE THREAD

**Issue by tviel** [rborn/nativescript-i18n#16]
Hi,
 anytime a change parts of my code and recompile, I get 

```
npm ERR! install trying to install 0.0.6 to C:\Projekte\git\app.pursUe\node_modules\nativescript-i18n
npm ERR! install but already installed versions [ '0.0.6',
npm ERR! install   '0.0.6',
npm ERR! install   '0.0.6',
npm ERR! install   '0.0.6',
npm ERR! install   '0.0.6',
npm ERR! install   '0.0.6',
npm ERR! install   '0.0.6',
npm ERR! install   '0.0.6',
npm ERR! install   '0.0.6',
npm ERR! install   '0.0.6',
npm ERR! install   '0.0.6' ]
```

array length increases from time to time.

however, app starts and works.

**Comment by rborn** [comment]
Mmm, looks more like a tooling problem. Somehow it doesn't seem to see the module is already installed.

**Comment by rborn** [comment]
@tviel I think this is the issue: https://github.com/NativeScript/nativescript-cli/issues/1990

**Comment by tviel** [comment]
Indeed it seems related. nativescript-i18n is a package I installed from this github instead using npm version, as the npm angular2 style is different then current state.
Is there an idea yet, when current github state will be pushed to npm?

**Comment by rborn** [comment]
Pushed  to npm 😄

**Comment by tviel** [comment]
Awesome. Works now with usual livesync cycle. Thx.
