### ISSUE TITLE
Unable to use plugin with Angular: angular.ts is not under 'rootDir'

### ISSUE THREAD

**Issue by michelebombardi** [rborn/nativescript-i18n#20]
I've followed the instructions to configure this plugin with angular project. When I try to build the project the following exception is shown:

`error TS6059: File 'C:/MyProject/node_modules/nativescript-i18n/angular.ts' is not under 'rootDir' 'C:/MyProject/app'. 'rootDir' is expected to contain all source files.`

Inside nativescript-i18n folder there is an angular.ts file (containing the pipe definition) but an angular.d.ts with typescript definitions should be present.

Fix it please :)

**Comment by rborn** [comment]
Hi,
I pushed to github a possible fix (**not published to npm yet**) Could you please give it a try?
Thank you.

**Comment by michelebombardi** [comment]
@rborn I tried your plugin again installing it from git hub repo directly. Now there are no errors during build but at runtime:

`The pipe 'L' could not be found`

I've included the plugin following the instructions in the main page so, in my _app.module.ts_:

```
import { NativeScriptI18nModule } from "nativescript-i18n/angular";     // to add Localization
...

@NgModule({
  imports: [
    ...
    NativeScriptI18nModule
  ]
  bootstrap: [AppComponent]
})
```

export class AppModule {}

Then, in my html layout:

`<ActionItem [text]="share | L" ....></ActionItem>`

What am I missing?

**Comment by Dragomir-Ivanov** [comment]
Any idea for the above error: "The pipe 'L' could not be found". I am getting the same.

**Comment by rborn** [comment]
@Dragomir-Ivanov I pushed a new version on npm, could you please have a look if it fixes the problem?
Thank you.

**Comment by Dragomir-Ivanov** [comment]
Now it works. Thanks a ton @rborn !
