### ISSUE TITLE
Can't Use Apostrophes Android

### ISSUE THREAD

**Issue by ghost** [rborn/nativescript-i18n#21]
@rborn Using apostrophes `'` in string definitions causes Android to not build; at the same time, it works on iOS so that means if you have a common codebase you can only remove the apostrophes.

Breaks in Android:
```xml
<string>Haven't</strong>
```
Works:
```xml
<string>Havent</string>
```

Please make it automatically escape these in Android when transpiling to Android's format.

**Comment by rborn** [comment]
Did you set `formatted="false"` ?

**Comment by ghost** [comment]
@rborn No, just `<string>`

**Comment by rborn** [comment]
Try the way is specified in the [docs](https://github.com/rborn/nativescript-i18n#important-) and let me know

```
<string name="something" formatted="false">Haven't</strong>
```

**Comment by ghost** [comment]
@rborn Isn't `formatted=false` only if we're using substitutions?  There's nothing about apostrophes in the docs

**Comment by rborn** [comment]
There is no "transpiling" for android, we just copy the resources files. 
You will need to escape the quotes as specified in the [Android documentation](https://developer.android.com/guide/topics/resources/string-resource.html#FormattingAndStyling)

**Comment by ghost** [comment]
@rborn The strings in iOS then have backslashes.  Duplicating the translation source files to be platform-specific for that reason only is not the most intuitive way to do things..

**Comment by rborn** [comment]
Ok, I'll have a look 👍

**Comment by ghost** [comment]
@rborn Any updates on this?

**Comment by rborn** [comment]
@vbresults new package on npm, let me know if it works on you.

**Comment by ghost** [comment]
It's strange, I didn't receive a notification about this update, it works now, thank you
