### ISSUE TITLE
Issue on iOs 10.1 iPhone 7 Plus emulator

### ISSUE THREAD

**Issue by devCrossNet** [rborn/nativescript-i18n#22]
I am really new to native script and I think I found an issue with i18n.

If I start my app with the iPhone 6s Plus emulator everything works fine. But not with iPhone 7 Plus.

Xcode 8.1, iOs 10.1 and I can reproduce it. Do you need more information?

Thanks for this great package!

**Comment by rborn** [comment]
What kind of issue? Would be good to have more details. Thank you.

**Comment by devCrossNet** [comment]
Hey, sorry for the late answer. I did not get an error or something. It was just displaying the default message instead of the translated message. I think you can close this if you can't reproduce it. Thx for your work!

**Comment by rborn** [comment]
Sorry, didn't have time to look into, life is hectic 😢

**Comment by devCrossNet** [comment]
![I feel you bro](https://cdn.meme.am/cache/instances/folder392/38384392.jpg)

**Comment by rborn** [comment]
@devCrossNet just pushed a new version on npm, could you have a look?
For me it works just fine now with 10.1 and 7+ emulator.

Thanks

**Comment by devCrossNet** [comment]
@rborn asap :-)

**Comment by rborn** [comment]
@devCrossNet I'll close this one, please re-open it if you find it happens again. Thanks 😄
