### ISSUE TITLE
Bump version and upload on npm

### ISSUE THREAD

**Issue by ghost** [rborn/nativescript-i18n#27]
@rborn Please bump the version and upload it on NPM so that the iOS 10 getter patch you made is available, otherwise apps crash on iOS 10

**Comment by rborn** [comment]
Can you confirm the fix works on both ios10 and 9.x ?
Thank you

**Comment by rborn** [comment]
Done, should be fine now 😄

**Comment by ghost** [comment]
@rborn I manually copied the patch before the npm update and yes it does work, thank you (:
