### ISSUE TITLE
Cannot get XML text="{{ L('example') }}" to work

### ISSUE THREAD

**Issue by terhoraj** [rborn/nativescript-i18n#3]
I have followed your tutorial and example app and done everything right I ques. I can access my strings from javascript just fine but from XML I always get "undefined" or something with console warning L is not a function or something (dont have my gear near at the moment). What am I doing wrong?

**Comment by rborn** [comment]
show me your app.js

**Comment by terhoraj** [comment]
![appjs](https://cloud.githubusercontent.com/assets/19226200/16292500/cfd96650-391a-11e6-83eb-1cd4411e47b7.PNG)

This is the error I get exactly: JS: Cannot find function or filter: L

**Comment by rborn** [comment]
What version of {N} are you using?

**Comment by terhoraj** [comment]
Version 2.0.1
Interesting, I created a new clean project and copied all relevant files from your demo project in it and it worked. This makes me think that might it have something to do with other plugins I use with the project that has problems. 

To explain what I have tried also is removing app from phone/AVD completely, removing platforms, rebuilding many times.

Anyway most interesting thing is that from javascript I can access those strings fine but from XML I only got "Cannot find function or filter: L" and if XML has something else before like {{ '*' + L('somestring') }} I got string "undefined" in to the UI + same error on console.

**Comment by rborn** [comment]
One more question: android or/and ios ?

I'll try to reproduce the issue in the weekend and let you know, but please let me know your platform.
Thank you.

**Comment by terhoraj** [comment]
Android. I'm using Windows 7 and 10 if that matters. Newest Nativescript.
I just made another clean project, this time I did not copy your project but made all as instructed. Got same error on first build and then after running tns remove platform android + building app multiple times It started to work. Locale and all works. When I edited strings and build again = fail. Run platform remove + build multiple times and works again. This same behaviour happens all the time with other plugins and stuff...

**Comment by rborn** [comment]
Ok, so it seems that somehow {N} is caching the platforms (to speedup the compile time)
What I do is to delete the `platforms` folders by hand, and not use `tns remove` and then run `tns run ios/android`

Can you try this please?
Thnx

**Comment by terhoraj** [comment]
It takes me couple of days to get back to the project. I certainly will. I'll post results here of course. Thanks for your awesome plugin and help so far!

**Comment by terhoraj** [comment]
Same thing no matter how many times I clean project out and compile. I always get "Cannot find function or filter: L" but not from code.

**Comment by rborn** [comment]
This is so weird. Let's try this:
- delete the **platforms**, **node-modules** and **hooks** folders
- go to package.json and remove the dependency of nativescript-i18n 
- run in console `tns plugin add nativescript-i18n`

And then try to run the project.
Let me konw

**Comment by terhoraj** [comment]
Yep, this is weird and it did not work. I'll keep trying everything out tho.

**Comment by terhoraj** [comment]
One more question popped in my mind and this might be a dummy question. When I go to i18n.android.js and there is that L functions.
Which one of these "application.resources.L = L;" or "global.L = L;" is called from xml and which one from javascript? questions should be more likely what happens after xml {{ L('xx') }}??

**Comment by rborn** [comment]
`application.resources.L` should be called in xml
`global.L` should be called in JS

**Comment by terhoraj** [comment]
Now I can say that the problems is not caused by your plugin anyway. I created a new clean project, got your plugin working right away. Started installing other plugins one by one + building again every time. No plugin related issues. After copy pasting app.js from original big project problems started to come back again. Something to do with application module.

**Comment by rborn** [comment]
When you say `Something to do with application module` you mean your app code or {N} application module?

**Comment by terhoraj** [comment]
My app code, must be.

**Comment by rborn** [comment]
Ok , I'll close the issue then 😄
I think you can reopen it anytime.

**Comment by terhoraj** [comment]
Lol, it was the original project code that somehow formatted application.resources so the problem is now solved. Your library works perfectly now, I'm an idiot...
