### ISSUE TITLE
Support formatting a string using parameters received from GCM.

### ISSUE THREAD

**Issue by spstratis** [rborn/nativescript-i18n#39]
I'm receiving `MissingFormatWidthException` when attempting to format a string with arguments received from the `title_loc_args`of a GCM message. 

I'm using GCM to send push notifications to my application, since the notifications need to be localized I can have the GCM payload contain the keys for the resource strings I want it to use. 

This works great when using the notification message param `"title_loc_key" : "some_key"`  to deal with a non-formatted string in which, when the message is received by the device it will match the key in this param to a key in my resource file and display the proper localized text. 

In the situation where I want to use a formatted string so that I can handle passing in dynamic values which need to be translated, I can add the `"title_loc_args"` to the notification body. So these two params from GCM would like this:

**Part of GCM message:**
`"title_loc_key" : "some_formatted_string",`
`"title_loc_args" : ["fname", "lname", "123"] `

And my resource string would look something like this below. In which Android is supposed to automatically pass the values into the found resource key as mentioned in the GCM documentation 
[found here](https://developers.google.com/cloud-messaging/http-server-ref#notification-payload-support) 

**Resource String** 
 `<string formatted="false" name="some_formatted_string">%s %s %s mg/dL</string>`

It appears that normally Android will automatically handle the string format replacement from the resource file, but the ns-i18n abstraction seems to have issues here since I'm not passing the args in the usual L('some_formatted_string', "fname", "lname", "123") format. 

Can you confirm if this is an issue or just not something supported by the plugin at this time? 

Thanks, everything else about it has worked great otherwise!

**Comment by rborn** [comment]
@spstratis can you show me how you pass the args? Show me a little code 😄

**Comment by spstratis** [comment]
@rborn So it ended up being a weird build issue :) closing this. Thanks for the quick response though.
