### ISSUE TITLE
Question: Any way to livesync for changes

### ISSUE THREAD

**Issue by ryc16** [rborn/nativescript-i18n#4]
Use the demo. Build and run it with llvesync. It works. However, when a new entry is added, even console saying

```
Transferring project files...
Successfully transferred all project files.
Applying changes...
```

But, it wouldn't work and got 

JS: Binding: Run-time error occured in file: undefined at line: undefined and column: undefined

Tried remove platform and add platform, still doesn't work. I finally figured out, I have to do uninstall the app (the demo) from the emulator (or phone) in order to work. I guess this might be due to resource wouldn't sync but this is really annoying as you know that it takes long time to build and deploy the package.

Is there any way to improve this experience? Or any trick to speed this up?

**Comment by terhoraj** [comment]
I have same problems and so far this problem is in nativescript it self.

**Comment by rborn** [comment]
Indeed, livesync won't sync resources and sadly I don't have any solution on how to fix this.

**Comment by jamlfy** [comment]
If not possible, that is android and iOS if you have to compile the apk or app. And get the strings, is direct in the code. And the code changes that are made have to be doing as compiled. It can be made is that the compiled string already have, and so we can recognize , but by injecting new strings in the xml, it's not possible.
