### ISSUE TITLE
TypeScript declarations?

### ISSUE THREAD

**Issue by lukeramsden** [rborn/nativescript-i18n#43]
TypeScript complains that `L` doesn't exist, so I'm assuming there are none?

**Comment by rborn** [comment]
@lukeramsden [this?](https://github.com/rborn/nativescript-i18n/blob/master/angular.ts)

**Comment by lukeramsden** [comment]
@rborn I'm not using Angular

**Comment by rborn** [comment]
@lukeramsden I'm not using nor angular nor ts... 😆  So yeah, there might be a problem.
Do you know any plugin that implements what you need so I can "steal" some code?

**Comment by lukeramsden** [comment]
@rborn Here is the declarations for tns-core-modules: https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/declarations.d.ts

Basically, all I did to fix it was put `declare var L: any;` in my `references.d.ts` in the root folder, so maybe its easier to put that in the README and let users do it if they need it?

**Comment by rborn** [comment]
Ok, could you try to add a `references.d.ts` file in the `/APP_PATH/node_modules/nativescript-i18n` folder with the above declaration, remove the declaration from the the root file and try again?

(you might need to also add some `/// <reference path` stuff ) like [here](https://github.com/EddyVerbruggen/nativescript-taptic-engine/blob/master/references.d.ts) but not sure 😸 

If it works then you could make a PR with the new file to the github project 😉 

Thanks a lot!

**Comment by rborn** [comment]
@lukeramsden Ok, merged, bumped version and published to npm, could you give it a shot with the normal npm install?

**Comment by rborn** [comment]
@lukeramsden Gonna close this, let me know if you fid new issues.
