### ISSUE TITLE
NSCalendarsUsageDescription translation

### ISSUE THREAD

**Issue by Habeeb-mohamed** [rborn/nativescript-i18n#45]
I am using the plugin 
https://github.com/EddyVerbruggen/nativescript-calendar

In plist.info i need to add the key to show the message before app accessing the calendar.

Can we show the message based on selected language?

**Comment by rborn** [comment]
Mmm, I need to dig more

**Comment by rborn** [comment]
Great, thanks again, published to npm 😄
