### ISSUE TITLE
NativeScript 3.0.0 support

### ISSUE THREAD

**Issue by toddanglin** [rborn/nativescript-i18n#47]
Creating an issue so we can track support readiness for NativeScript 3.0.0. I've identified at least one thing in my local testing that needs to be changed to make this plugin work with 3.0.0. There might be more.
 
- [x] Change references to `application.resources` to use new API (`application.getResources()`)
- [x] Use new plugin APIs to support LiveSync in 3.0.0

Will submit a PR for issues that I can address if they don't get patched first. Hopefully we can have full support for 3.0.0 before it ships in a couple weeks.

**Comment by PieterAelse** [comment]
Any updates on this? NativeScript 3.0.0 seems to be released according to the table when I run `tns info`
> All NativeScript components versions information

| Component                  | Current version  | Latest version | Information |
|--|--|--|--|
| nativescript                 |  3.0.0                          | 3.0.0         | Up to date       |
| tns-core-modules       | 3.0.0           | 3.0.0          | Up to date       |
| tns-android                 | 3.0.0          | 3.0.0          | Up to date       |
| tns-ios                         | 2.5.0           | 3.0.0          | Update available |

**Comment by lukeramsden** [comment]
Yeah, I tried updating all my dependencies and the app stopped compiling. Complaining about the use of L().

**Comment by spstratis** [comment]
@lukeramsden That issue is more than likely caused by the improper use of the `application.resources` which changed in 3.0.  You may be able to change the package locally in order to fix it. It may still break with the livesync related issue though.

**Comment by rborn** [comment]
@toddanglin could you please have a look at [this branch](https://github.com/rborn/nativescript-i18n/tree/fix_tns_3_0_0)?
it behaves a little odd and I don't know why:

- if I edit a **xml** file it goes fine most of the times (sometimes iOS rebuilds the project once, but I don't know why, android is fine)
- if I edit a **js** file iOS crashes, if I save the file again it syncs fine without rebuilding (so for js files and iOS it needs 2 "save"), android restarts the app so it's fine
- if I edit a **language** file it rebuilds the project and restarts the app (this is how it should be I think) - both platforms

Thank you :)

Crash attached (Sim with iPhone 7 Plus, 10.3, Xcode 8.3.2)
```
Executing before-prepare hook from /Work/mine/nativescript-i18n/demo/hooks/before-prepare/nativescript-i18n.js
Preparing project...
Project successfully prepared (ios)
Transferring project files...
Successfully transferred main-view-model.js.
Refreshing application...
An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=3):
The request to open "org.nativescript.nativescripti18ndemo" failed.
The process did launch, but has since exited or crashed.
Unable to sync files. Error is: Multiple errors were thrown:
Error Command failed: xcrun simctl launch 68A69D5D-37F3-41AF-B953-C7BCF277DB0D org.nativescript.nativescripti18ndemo
An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=3):
The request to open "org.nativescript.nativescripti18ndemo" failed.
The process did launch, but has since exited or crashed.
 while executing xcrun simctl launch 68A69D5D-37F3-41AF-B953-C7BCF277DB0D org.nativescript.nativescripti18ndemo.
May  5 13:49:54 Spawn CoreSimulatorBridge[1581]: Pasteboard change listener callback port <NSMachPort: 0x7f8487723740> registered
May  5 13:49:55 Spawn SpringBoard[1575]: [KeyboardArbiter] HW kbd: Failed to set (null) as keyboard focus
May  5 13:49:55 Spawn com.apple.CoreSimulator.SimDevice.68A69D5D-37F3-41AF-B953-C7BCF277DB0D.launchd_sim[1558] (UIKitApplication:org.nativescript.nativescripti18ndemo[0x9841][1580][19747]): Service exited due to Terminated: 15
May  5 13:49:55 Spawn backboardd[1576]: [Common] Unable to get short BSD proc info for 19747: No such process
May  5 13:49:55 Spawn backboardd[1576]: [Common] Unable to get proc info for 19747: Undefined error: 0
May  5 13:49:55 Spawn CoreSimulatorBridge[1581]: Pasteboard change listener callback port <NSMachPort: 0x7f848a32d690> registered
May  5 13:49:55 Spawn CoreSimulatorBridge[1581]: Requesting launch of org.nativescript.nativescripti18ndemo with options: {
	    environment =     {
	    };
	}
May  5 13:49:55 Spawn CoreSimulatorBridge[1581]: Beginning launch sequence for bundle 'org.nativescript.nativescripti18ndemo'
		retryTimeout: 120.000000 (default write com.apple.CoreSimulatorBridge LaunchRetryTimeout <value>)
		bootTimeout: 300.000000 (default write com.apple.CoreSimulatorBridge BootRetryTimeout <value>)
		bootLeeway: 120.000000 (default write com.apple.CoreSimulatorBridge BootLeeway <value>)
		Note: Use 'xcrun simctl spawn booted defaults write <domain> <key> <value>' to modify defaults in the booted Simulator device.
	Simulator booted at: 2017-05-05 10:26:17 +0000
	Current time: 2017-05-05 11:49:55 +0000
	Within boot leeway: NO
May  5 13:49:55 Spawn CoreSimulatorBridge[1581]: Launch attempt #0 for bundle 'org.nativescript.nativescripti18ndemo', have been trying to launch for 0 seconds. Modern launch services = YES
May  5 13:49:55 Spawn CoreSimulatorBridge[1581]: Got LSBundleProxy for 'org.nativescript.nativescripti18ndemo', sequenceNumber 388, cacheGUID BC9A763B-962E-4562-BCD1-E41214A113F8
May  5 13:49:55 Spawn CoreSimulatorBridge[1581]: [Common] [FBSSystemService][0xb299] Sending request to open "org.nativescript.nativescripti18ndemo"
May  5 13:49:55 Spawn CoreSimulatorBridge[1581]: [Common] [FBSSystemService][0xb299] Error handling open request for org.nativescript.nativescripti18ndemo: <NSError: 0x7f848762b560; domain: FBSOpenApplicationServiceErrorDomain; code: 3 (ProcessExited); reason: "The process did launch, but has since exited or crashed."> {
	    description = "The request to open "org.nativescript.nativescripti18ndemo" failed.";
	    failureReason = "The process did launch, but has since exited or crashed.";
	}
May  5 13:49:55 Spawn CoreSimulatorBridge[1581]: Error Launching: Error Domain=FBSOpenApplicationServiceErrorDomain Code=3 "The request to open "org.nativescript.nativescripti18ndemo" failed." UserInfo={NSLocalizedFailureReason=The process did launch, but has since exited or crashed., BSErrorCodeDescription=ProcessExited, NSLocalizedDescription=The request to open "org.nativescript.nativescripti18ndemo" failed.}
May  5 13:49:55 Spawn CoreSimulatorBridge[1581]: Non-FBS error launching 'org.nativescript.nativescripti18ndemo', will NOT retry. Error was: Error Domain=FBSOpenApplicationServiceErrorDomain Code=3 "The request to open "org.nativescript.nativescripti18ndemo" failed." UserInfo={NSLocalizedFailureReason=The process did launch, but has since exited or crashed., BSErrorCodeDescription=ProcessExited, NSLocalizedDescription=The request to open "org.nativescript.nativescripti18ndemo" failed.}
May  5 13:49:55 Spawn assertiond[1580]: Ignoring assertion request named "Deliver Message" from <BSProcessHandle: 0x7fef33701080; SpringBoard:1575; valid: YES> because process { pid 19747; bundleID (null) } is unknown.
May  5 13:49:55 Spawn assertiond[1580]: Ignoring assertion request named "FBSceneSnapshotAction:org.nativescript.nativescripti18ndemo" from <BSProcessHandle: 0x7fef33701080; SpringBoard:1575; valid: YES> because process { pid 19747; bundleID (null) } is unknown.
```

**Comment by simplec-dev** [comment]
I figured out a fix.

in i18n.android.js and i18n.ios.js change application.resources.L = L to application.setResources({L: L});

Then, in angular.ts add this to the top:
var application = require("application");

Then change the "return global.L(value, ...more);" to 
return application.getResources().L(value, ...more);

**Comment by rborn** [comment]
@simplec-dev I did that, iOS still crashes when editing a js file 😢 
Please have a look, maybe you find something.

**Comment by kssfilo** [comment]
I modified like below and working fine.

```
< import application from 'application';
---
> import * as application from 'tns-core-modules/application';

<         application.getResources().L(value, ...more);
---
>         return application.getResources().L(value, ...more);
```

**Comment by rborn** [comment]
@kssfilo added the changes you suggested. My demo app still crashes on iOS when editing the `main-view-model.js` file. If I re-save the file, the app will start again with the changes, so it needs to be saved twice, first time will crash, the second time will start ok (no need to interact with the simulator in any way). Can you confirm this? 
Thank you.

**Comment by kssfilo** [comment]
I confirmed commit 34fad with my angular app and seems ok. 

About the JS file editing issue, I am same but I saw this problem on tns 2.x.x with iOS emulator. 

I removed nativescript-i18n from your demo app.  but the problem still remains.

so maybe it's not i18n tns 3.0.0 specific problem.

**Comment by rborn** [comment]
@kssfilo Ok, thanks a lot, I'll open a ticket with nativescript.

**Comment by rborn** [comment]
0.2.0 published  to npm  🎉
