### ISSUE TITLE
How to change the language at runtime

### ISSUE THREAD

**Issue by ryc16** [rborn/nativescript-i18n#5]
Is there any way to switch the language at runtime rather than on the phone itself? Couldn't find this information.

**Comment by rborn** [comment]
The plugin uses the native mechanism provided by the OS. 
An android it might be possible, but with a lot of trouble (I mean for this plugin) while on iOS you would need to find a way to "reboot" the whole app - not sure this is possible in {N} 

If you want to do this, you would need to make your own i18n routine, probably an observable associated to an array/object which you will change at some point from within the app.

**Comment by ryc16** [comment]
Thank you for your answer. I was hoping if there is anything like angular's translate which should be able to change language at runtime. I might not want to use angular just because of using angular's translate.
