### ISSUE TITLE
Are there additional build steps?

### ISSUE THREAD

**Issue by slushpuppy** [rborn/nativescript-i18n#56]
1. cd'd into my project directory
2. ran the npm install command
3. inserted the strings.xml
4. required globals & nativescript-i18n

Upon running the code, it shows that L('string') returns empty string & it appears that L is not defined at all.

I have deleted the app and reinstalled it to no end.

Running off pures JS in nativescript, not angular.

I will be grateful for nay assistance

Thank you

**Comment by rborn** [comment]
Is the [demo](https://github.com/rborn/nativescript-i18n/tree/master/demo) building for you?

**Comment by slushpuppy** [comment]
@rborn Thanks for the reply, how do i install & run the demo?(I am new to nativescript)

**Comment by rborn** [comment]
clone the repo, cd into demo, then `tns run ios`
this should do it :)

the only difference between the demo and your project is the path of the plugin in the package.json file -  the demo takes it from local while your project from npm.

**Comment by slushpuppy** [comment]
Demo works perfectly fine.. hmm, are there any debugging steps I could take to remedy the action in my project? I have the following debug code:

> <?xml version="1.0" encoding="utf-8"?>
> <resources>
>   <string name="app_name">My app</string>
>   <string name="title_activity_kimera">My App</string>
>   <string name="capture_page_title">Capture Save</string>
>   <string name="take_photo_title">Camera</string>
> </resources>


Inside app.js

> require('globals');
> require('nativescript-i18n');
> 
> var applicationModule = require("application");
> applicationModule.start({ moduleName: "ui/capture-page" });

capture-page.js

> 
> exports.pageLoaded = function() {
>   if (L && typeof L === 'function') {
>     console.log('sdsfd');
>   }
> console.log(L('capture_page_title'));
> console.log(typeof L);
> };

capture-page.xml

> <Page loaded="pageLoaded">
>   <ActionBar title="{{ L('capture_page_title') }}">
>     <android>
>       <ActionItem tap="newProject"
>       ios.systemIcon="16" ios.position="right"
>       text="New Survey Project" android.position="popup"/>
>       etc...

debug output:

> JS: sdsfd
> JS: capture_page_title
> JS: function
>

**Comment by rborn** [comment]
So `L` it's there, we must find the missing texts :)
Where do you have the `strings.xml` files? (show me the full path relative to the app's root)

**Comment by slushpuppy** [comment]
Oops I think the XML didn't paste properly, here it is:

`<?xml version="1.0" encoding="utf-8"?>
<resources>
  <string name="app_name">myApp</string>
  <string name="title_activity_kimera">myApp</string>
  <string name="capture_page_title">Capture Save</string>
  <string name="take_photo_title">Camera</string>
  <string name="estimate_range_title">Estimate Range</string>
</resources>
`

strings.xml -> myApp\app\App_Resources\i18n\en\strings.xml

**Comment by rborn** [comment]
Ok, the path is wrong - the docs say `Create a folder i18n in the app folder with the following structure:` so maybe you were mislead by the fact that App_Resources is there too in the example?

So try:
strings.xml -> `myApp\app\i18n\en\strings.xml`

**Comment by slushpuppy** [comment]
Thanks for the reply, still no go:

myApp\app\i18n\en\strings.xml

Is my strings.xml format correct?

**Comment by slushpuppy** [comment]
do not that myApp\app\Packages.json

> {
>   "android": {
>     "v8Flags": "--expose_gc"
>   },
>   "main": "app.js",
>   "name": "tns-template-hello-world",
>   "version": "3.0.0"
> }

**Comment by rborn** [comment]
Yes  strings it's ok
the package.json in app is generated by NS, don't touch it :)

- cd in the myApp folder (root of the app)
- run `npm install --save nativescript-i18n`
- delete `hooks, node_modules, platforms` from the root of the app folder (so inside myApp, same level with app)
- tns run ios

**Comment by slushpuppy** [comment]
Done that, still no go: But i noticed the following:

Project successfully created.
Executing before-prepare hook from C:\Nativescript\myApp\hooks\before-prepare\nativescript-dev-android-snapshot.js
Executing before-prepare hook from C:\Nativescript\myApp\hooks\before-prepare\nativescript-i18n.js
Preparing project...

So it does appear to hook on correctly

**Comment by rborn** [comment]
Can you make  a zip with your app folder (delete the folders I told you first) and send it over to have a look?

**Comment by slushpuppy** [comment]
[app.zip](https://github.com/rborn/nativescript-i18n/files/989263/app.zip)
Thanks for your patience!

**Comment by rborn** [comment]
I need the whole app, so `myApp` folder, not only the `app` folder :)

**Comment by slushpuppy** [comment]
Sorry!
[myApp.zip](https://github.com/rborn/nativescript-i18n/files/989280/myApp.zip)

**Comment by rborn** [comment]
I just unpacked your project, cd in myApp and run `tns run ios` and `tns run android`
The JS shows L working ok, but the xml is not 😐 

I will need some time to investigate

**Android:**
```
Transferring project files...
Successfully transferred all files.
Refreshing application...
Successfully synced application org.nativescript.myApp on device 4641190115e73f9e.

JS: sdsfd
JS: Capture Save
JS: function
```
**iOS:**
```
Project successfully built.
Installing...
Successfully installed on device with identifier '68A69D5D-37F3-41AF-B953-C7BCF277DB0D'.
Transferring project files...
Successfully transferred all files.
Refreshing application...
No matching processes belonging to you were found
Successfully synced application org.nativescript.myApp on device 68A69D5D-37F3-41AF-B953-C7BCF277DB0D.

objc[62227]: Class PLBuildVersion is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/AssetsLibraryServices.framework/AssetsLibraryServices (0x11b070cc0) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices (0x11ae876f0). One of the two will be used. Which one is undefined.
CONSOLE LOG file:///app/ui/capture-page.js:3:16: sdsfd
CONSOLE LOG file:///app/ui/capture-page.js:5:12: Capture Save
CONSOLE LOG file:///app/ui/capture-page.js:6:12: function
```

**Comment by slushpuppy** [comment]
Yup. same results on my end. 

Thank you so much.

**Comment by rborn** [comment]
You forgot to bind the data to the model
do this in `capture-page.js`
```
var Observable = require('data/observable').Observable;

function pageLoaded(args) {
    var page = args.object;
    page.bindingContext = new Observable();
}

exports.pageLoaded = pageLoaded;
```

(estimate_range_title is missing from the strings.xml)
![screen shot 2017-05-10 at 12 38 05](https://cloud.githubusercontent.com/assets/406409/25894803/a24b5c42-357d-11e7-9d4f-ffff49d25fdf.png)

**Comment by slushpuppy** [comment]
Thanks! I guess i will need that snippet for every file that includes L()?

**Comment by rborn** [comment]
You need this for every file that has a `{{ some_variable }}` in xml
[Read more about data binding :) ](https://docs.nativescript.org/core-concepts/data-binding)

**Comment by slushpuppy** [comment]
Thank you so much!

**Comment by rborn** [comment]
If all works ok, can we close the issue? 😄
