### ISSUE TITLE
translate programmatically with Angular 2

### ISSUE THREAD

**Issue by magar91** [rborn/nativescript-i18n#57]
how can I call the L() function to translate programmatically inside of a .ts class component instead of an .html? I used to be able to do it with `global.L()` in previous versions of nativescript but with the new version 3.0.1 I can't use the global variable as I used to

**Comment by rborn** [comment]
@magar91 I don't know, no change was made to the way I declare L in the global scope.

**Comment by rborn** [comment]
@magar91 do you put `require("globals");` at the beginning of your file?

**Comment by magar91** [comment]
I'm using the plugin with angular 2 but I didn't use `require("globals")` before and it worked fine, I will try adding it. I'll come back with an answer soon

**Comment by magar91** [comment]
@rborn I tried doing adding `require("globals")` but still I can't call the L() function in my .ts file, any idea how I can use the L() function?

EDIT:
I looked around the project issues and found [this](https://github.com/rborn/nativescript-i18n/issues/47#issuecomment-299820103)

I added the following import to my .ts file
```javascript
import * as application from "tns-core-modules/application";
```
and used the L() function like this
```javascript
application.getResources().L(value);
```
I can use the L() function now inside my .ts class

**Comment by rborn** [comment]
@magar91 Thank you
I opened [this ticket](https://github.com/NativeScript/NativeScript/issues/4222) to see why it's doing this.

**Comment by rborn** [comment]
@magar91 there are some replies in the NS ticket, could you give them a shot?
Thank you.

**Comment by magar91** [comment]
Hi @rborn I tried adding this `declare var global : any;` as suggested [here](https://github.com/NativeScript/NativeScript/issues/4222#issuecomment-302365246) and it works perfectly

**Comment by rborn** [comment]
@magar91 where did you do this? can it be done in the plugin? So it becomes seamless for other devs?

**Comment by magar91** [comment]
I added it in the file where I used the function, here is an example of where I used it:

```javascript
import { Component, OnInit } from "@angular/core";

import { Item } from "./item";
import { ItemService } from "./item.service";

declare var global:any;

@Component({
    selector: "ns-items",
    moduleId: module.id,
    templateUrl: "./items.component.html",
})
export class ItemsComponent implements OnInit {
    items: Item[];

    constructor(private itemService: ItemService) { }

    ngOnInit(): void {
        console.info(global.L("translate"))
        this.items = this.itemService.getItems();
    }
}
```
to be honest I don't know if it can be done in the plugin, I'm sorry

**Comment by rborn** [comment]
ok, thank you, I'll update the docs with your explanations 👍

**Comment by isamilo** [comment]
anyone can help please "ERROR in ../node_modules/nativescript-i18n/angular.ts
Module build failed (from ../node_modules/@ngtools/webpack/src/index.js):
Error: D:\Projects\masaa manne\BarPoint\node_modules\nativescript-i18n\angular.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property"
I try to use localization in my Project
