### ISSUE TITLE
ERROR ITMS-90087: "Unsupported Architectures" when uploading to App Store

### ISSUE THREAD

**Issue by ghost** [rborn/nativescript-i18n#58]
I've just started to upload the app (TNS 2.5.2) via the application loader and got:

`ERROR ITMS-90087: "Unsupported Architectures. The executable for JOSERASalesSupport.app/app/tns_modules/nativescript-i18n/node_modules/tns-core-modules-widgets/platforms/ios/TNSWidgets.framework contains unsupported architectures '[x86_64, i386]'."`

`ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'JOSERASalesSupport.app/app/tns_modules/nativescript-i18n/node_modules/tns-core-modules-widgets/platforms/ios/TNSWidgets.framework/TNSWidgets' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."`

`WARNING ITMS-90080: "The executable 'Payload/JOSERASalesSupport.app/app/tns_modules/nativescript-i18n/node_modules/tns-core-modules-widgets/platforms/ios/TNSWidgets.framework' is not a Position Independent Executable. Please ensure that your build settings are configured to create PIE executables. For more information refer to Technical Q&A QA1788 - Building a Position Independent Executable in the iOS Developer Library."`

`ERROR ITMS-90685: "CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'org.nativescript.TNSWidgets' under the iOS application 'JOSERASalesSupport.app'."`

`ERROR ITMS-90125: "The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker."`

**Comment by rborn** [comment]
I'm not sure, this must be something on the NS side, you might wanna open a ticket with them.

**Comment by ghost** [comment]
You're right. It was a problem on the NS side. Could help me with "`tns platform remove ios`" and "`tns platform add ios`". Thanks!
