### ISSUE TITLE
Cannot find module nativescript-i18n

### ISSUE THREAD

**Issue by uioporqwerty** [rborn/nativescript-i18n#59]
I added the following lines to my app.ts file but I get the error that TypeScript cannot find the module nativescript-i18n:

```
import * as global from 'globals';
import * as i18n from 'nativescript-i18n';

// Initialize i18n
declare var global : any;
```

I've tried removing node_modules and then reinstalling but no luck :( using ```import * as i18n from 'nativescript-i18n/angular'``` works, however I'm not using angular.

**Comment by rborn** [comment]
I'm not sure, do you have a test project to play with?

**Comment by rborn** [comment]
Closing for lack of reply, if you still have the issue please re-open with more details. Thank you.
