### ISSUE TITLE
[android, npm] can't webpack uglify

### ISSUE THREAD

**Issue by ghost** [rborn/nativescript-i18n#62]
@rborn 0.2.1 doesn't work with nativescript-dev-webpack's uglify option because this line uses `let` (ES6):

https://github.com/rborn/nativescript-i18n/blob/master/i18n.android.js#L12

Uglify does not parse ES6.  In the `master` branch this seems to be fixed already (:

Please publish this fix to NPM (:

**Comment by rborn** [comment]
@vbresults done, sorry for this 😄
