### ISSUE TITLE
update issue

### ISSUE THREAD

**Issue by abolinhas** [rborn/nativescript-i18n#63]
Hi,
Every time that I add or change a new string in XML i need to remove the platform and add again to get access to the values of this strings.

**Comment by rborn** [comment]
I don't think it's possible without doing it so. 
Can you make a small test project where I can see the behaviour?
Thank you.

**Comment by d3mac123** [comment]
@abolinhas is right. Everytime a new string in the strings.xml file is added, a remove platform is required.

**Comment by abolinhas** [comment]
@rborn I create a helloword project and install your plugin.
I add multiple new strings into strings.xml then I did tns prepare android && tns build android && tns run android, in all cases the new strings is nos added to the project.
The only way that i find to add new strings into the project is remove and add the platform..
The before-prepare.js update the sting file inside app/app_resources/Android/values but not inside the string file inside platforms/Android/src/main/res/values

**Comment by rborn** [comment]
I'm afraid we'll have to live with this for now 😞
