### ISSUE TITLE
Not working :(

### ISSUE THREAD

**Issue by d3mac123** [rborn/nativescript-i18n#64]
I have followed all the steps in the documentation but I couldn't make the plugin to work (both Android and iOS emulators). For all:
`console.log(L('hello'));`

...instead of getting the right message:
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="app_name">PPG Finder</string>
    <string name="title_activity_kimera">PPG Finder</string>
    <string name="hello">Hello!</string>
</resources>
```

...I just get the name of the string. In the example above:
`hello`

I have deleted the apps in the devices, as well as re-build them. Any ideas?

**Comment by rborn** [comment]
Do you have the strings files in the right place?

Keep in mind that you can set a customPath in package.json https://github.com/rborn/nativescript-i18n/blob/master/demo/package.json#L27

**Comment by d3mac123** [comment]
It is inside App_Resources/i18n, as suggested in the main documentation. I've tried also to move it to another path (using the customPath) but it still did not worked. When I do that, I get the following error:
```
Executing before-prepare hook from /Users/alexsouza/ppgFinder/hooks/before-prepare/nativescript-i18n.js
Unable to apply changes on device: 46F35FE8-4C4C-45AD-887D-51766DE2A4F1. Error is: ENOTDIR: not a directory, open '/Users/alexsouza/ppgFinder/app/i18n/.DS_Store/strings.xml'.
```
![screen shot 2017-07-20 at 8 04 14 am](https://user-images.githubusercontent.com/229148/28416460-1c60af38-6d22-11e7-87ce-c4dde6ea5986.png)

**Comment by rborn** [comment]
Your customPath seems to be weird `/Users/alexsouza/ppgFinder/app/i18n/.DS_Store/strings.xml` (why `.DS_Store` ?)
Anyway, try to leave it in the recommended  place but empty the platform folder so NS builds again.

**Comment by d3mac123** [comment]
Sorry to ask such dumb question but, how can I do that? Just delete the full /ios folder under /platforms?

**Comment by rborn** [comment]
yes :)

**Comment by d3mac123** [comment]
Did not worked :(

See what I have:
- app.js (first lines):
```
require('globals');
require('nativescript-i18n');
```

- main.xml:
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="onNavigatingTo" class="page" xmlns:x="nativescript-statusbar" backgroundSpanUnderStatusBar="true"  backgroundColor="#171b1c">
    <Page.actionBar>
        <ActionBar title="PPG Finder" icon="" class="action-bar" backgroundColor="#182126">
        </ActionBar>
    </Page.actionBar>
    <x:StatusBar ios:barStyle="light" android:barStyle="#182126" />
    
    <GridLayout columns="*" rows="*,60,60,50" class="loginButtons">
    <Label text="{{ L('hello') }}" row="0" />
        <Button text="FACEBOOK LOGIN" tap="{{ onTap }}" row="1" class="btn btn-primary btn-active butFace"/>
        <Button text="EMAIL LOGIN" tap="{{ onTapEmail }}" row="2" class="btn btn-primary btn-active butEmail"/>
        <Label text="{{ L('version'), 'version' }}" textWrap="true" class="version" row="3" horizontalAlignment="center"/>
    </GridLayout>
</Page>
```

strings.xml (under App_Resources/i18n/en):
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="app_name">PPG Finder</string>
    <string name="title_activity_kimera">PPG Finder</string>
    <string name="hello">Hello!</string>
        <string name="noConnectivity">You are not connected with the Internet. Please connect in order to see maps and other pilots.</string>
        <string name="wifiConnectivity">Wifi Connection.</string>
        <string name="mobileConnectivity">Mobile Connection.</string>
        <string name="FacebookLogin">FACEBOOK LOGIN</string>

        <string formatted="false" name="version">version %s</string>
</resources>
```
- package.json:
```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "com.asouza.ppgFinder",
    "tns-android": {
      "version": "3.1.1"
    },
    "tns-ios": {
      "version": "3.1.0"
    }
  },
  "dependencies": {
    "nativescript-appversion": "^1.4.1",
    "nativescript-directions": "^1.0.5",
    "nativescript-dom": "^2.0.0",
    "nativescript-feedback": "^1.0.5",
    "nativescript-geolocation": "^3.0.0",
    "nativescript-i18n": "^0.2.2",
    "nativescript-imagepicker": "^3.0.1",
    "nativescript-insomnia": "^1.2.1",
    "nativescript-mapbox": "^3.0.1",
    "nativescript-orientation": "^1.6.1",
    "nativescript-permissions": "^1.2.3",
    "nativescript-plugin-firebase": "^4.0.3",
    "nativescript-pulltorefresh": "^2.0.1",
    "nativescript-screenshot": "0.0.2",
    "nativescript-social-share": "^1.3.2",
    "nativescript-statusbar": "^3.0.1",
    "nativescript-telerik-ui": "^3.0.4",
    "nativescript-theme-core": "~1.0.2",
    "tns-core-modules": "^3.1.0",
    "tns-core-modules-snapshot": "3.0.1-5.5.372.32"
  },
  "devDependencies": {
    "babel-traverse": "6.24.1",
    "babel-types": "6.24.1",
    "babylon": "6.17.2",
    "lazy": "1.0.11",
    "nativescript-custom-entitlements": "^0.2.0",
    "nativescript-dev-android-snapshot": "^0.*.*"
  }
}
```
Am I missing anything else?

**Comment by rborn** [comment]
Sorry, I misread the i18n location part. 
The docs say `Create a folder i18n in the app folder with the following structure:` so **not** inside the **App_Resources**, but in **app**.
Move the i18n folder one level up and let me know

**Comment by d3mac123** [comment]
I had noticed it and moved (and I deleted the platform folder) - it did not work. Error message:
`Unable to apply changes on device: 46F35FE8-4C4C-45AD-887D-51766DE2A4F1. Error is: ENOTDIR: not a directory, open '/Users/alexsouza/ppgFinder/app/i18n/.DS_Store/strings.xml'.`

For some reason, creating folders from inside VS Code adds this ".DS_Store" thing. Doing it from Terminal made it work.

Thank you very much for your kind support!

**Comment by rborn** [comment]
So it's fixed?
About vscode, I have this in settings, maybe it helps:
~~~
  // Configure glob patterns for excluding files and folders.
  "files.exclude": {
    "**/.git": true,
    "**/.svn": true,
    "**/.hg": true,
    "**/CVS": true,
    "**/.DS_Store": true
  },
~~~

**Comment by d3mac123** [comment]
It is fixed. Creating the folders via Terminal removed that strange ".DS_Store" string.

**Comment by sushant-j** [comment]
Hello..
I recently started working with {N} and have installed this plugin. I'm facing the same issue where I can't get the strings in my XML files, though if I print them out in JS logs, they show up properly. 

My i18n folder is in the app/ directory, and I have `require`-d both globals and nativescript-i18n before application in app.js.

Any help please? Thanks :)

**Comment by rborn** [comment]
@sushant-j really sorry, I'm not into {N} anymore, so I didn't keep track on the changes they did.

**Comment by sushant-j** [comment]
Oh.. That's unfortunate. Anyways, thanks for your reply!
