### ISSUE TITLE
errors on tns Run - JS ERROR Error: A Frame must be used to navigate to a Page

### ISSUE THREAD

**Issue by noordw** [rborn/nativescript-i18n#65]
These warnings first
CONSOLE WARN file:///app/tns_modules/nativescript-i18n/node_modules/tns-core-modules/utils/utils.js:113:14: Objective-C class name "UIDocumentInteractionControllerDelegateImpl" is already in use - using "UIDocumentInteractionControllerDelegateImpl1" instead.
CONSOLE WARN file:///app/tns_modules/nativescript-i18n/node_modules/tns-core-modules/ui/gestures/gestures.js:16:14: Objective-C class name "UIGestureRecognizerDelegateImpl" is already in use - using "UIGestureRecognizerDelegateImpl1" instead.
CONSOLE WARN file:///app/tns_modules/nativescript-i18n/node_modules/tns-core-modules/ui/gestures/gestures.js:28:14: Objective-C class name "UIGestureRecognizerImpl" is already in use - using "UIGestureRecognizerImpl1" instead.

tns 3.1.3
tns-core 3.1.1

Also get the Similar errors  on android

**Comment by ghost** [comment]
@rborn +1 this is happening for me too using `nativescript@rc` (3.2.0).  I believe this is because `tns-core-modules` is a dependency instead of a devDependency.

This results in it overriding the correct/main project's `tns-core-modules`.

```
file:///app/tns_modules/nativescript-i18n/node_modules/tns-core-modules/application/application.js:196:75: JS ERROR Error: A Frame must be used to navigate to a Page.
```

**Comment by rborn** [comment]
@noordw @vbresults 0.2.3 published to npm, I tested with the demo app in the repo and it starts fine. Please have a look and let me know.

**Comment by ghost** [comment]
@rborn Not working for me, as I mentioned, it's overriding the main project's `tns-core-modules` and changing it's version will not solve it -- it needs to be moved from dependencies to devDependencies.

**Comment by rborn** [comment]
@vbresults did you test it with devDependencies and it works?

**Comment by ghost** [comment]
@rborn I did and it works

**Comment by rborn** [comment]
@vbresults done and published, could you give it a try?
Thanks a lot for the help 🤗

**Comment by ghost** [comment]
@rborn Works, thank you!

**Comment by mid787** [comment]
Wow. had this problem : 

![image](https://user-images.githubusercontent.com/2842123/33527423-86b346a0-d859-11e7-97cb-73bb88b6fec8.png)

moved from A to B : 

![image](https://user-images.githubusercontent.com/2842123/33527431-9ceae608-d859-11e7-9abd-4b7d8026ffbe.png)

And it worked. THANKS
