### ISSUE TITLE
Change language file when i click button?

### ISSUE THREAD

**Issue by vijaykumarbollavaram** [rborn/nativescript-i18n#66]
I have following code in app.js

```
require("tns-i18n")('ar');
require("./bundle-config");
var application = require("application");
application.start({ moduleName: "views/splash/splash" });`
```

In my splash screen I have 3 buttons , French, English, Arabic. When I tap on any buitton that language file should be load in application. How to solve this problem

Like for english `require("tns-i18n")('en');`

**Comment by rborn** [comment]
Sorry but for now there you cannot change the language at the runtime. A PR is welcomed though 😄

**Comment by rborn** [comment]
Closing, same as #60
