### ISSUE TITLE
Maintainer wanted!

### ISSUE THREAD

**Issue by rborn** [rborn/nativescript-i18n#67]
I moved away from NativeScript so I'm looking for somebody to take ownership of the plugin and continue the development of it.

**Comment by jamlfy** [comment]
HI!!! You need a dev?

**Comment by rborn** [comment]
@alejonext Hi,  I need somebody to take over the plugin, I don't use NS anymore so I won't update it.

**Comment by donaldking** [comment]
Hi, I dont mind taking over from here @alejonext

**Comment by jamlfy** [comment]
Ok, but to start sending patches: D

**Comment by odnamrataizem** [comment]
What's the status of this? I'd love to take over the plugin if it's still up for grabs.

**Comment by rborn** [comment]
@odnamrataizem thanks for the offer 🤗
I'd love to see some PRs made first , as @alejonext suggested too and I can add you as collaborator 😊

**Comment by AsrarMemon** [comment]
Hi,
What's the status of this?
i can improve this plugin.
if you want i can continue the development of it.

**Comment by rborn** [comment]
@AsrarMemon thanks, you can start sending PRs, if all goes fine I'll add you as collaborator to the repo 🤗

**Comment by xlmnxp** [comment]
I can do it and help you

**Comment by rborn** [comment]
@xlmnxp invited :)

**Comment by xlmnxp** [comment]
@rborn accepted :D
can you publish new version to npm?

**Comment by rborn** [comment]
@xlmnxp done 🎉

**Comment by EddyVerbruggen** [comment]
Hi @rborn, if you want to permanently move this repo to a new owner, then I'm volunteering to adopt this repo. I will still depend on external contributors, but I do have time to do a little maintenance. If you're OK with it, please move it to my account and add me as a (co)owner on the npm package as well.

Good luck with your new activities, and thanks for creating and maintaining this repo!

**Comment by rborn** [comment]
Hi Eddy, yes that would be awesome, especially you are really familiar with NS so it would go a good place 🤗

**Comment by EddyVerbruggen** [comment]
Thanks, that's much appreciated, I'll take good care of your project mate!

**Comment by rborn** [comment]
Getting this:
<img width="451" alt="Screenshot 2019-07-05 at 09 59 32" src="https://user-images.githubusercontent.com/406409/60707299-b1ebfb80-9f0b-11e9-9d3e-728ae9578a17.png">

**Comment by EddyVerbruggen** [comment]
Ha! That's my fork blocking the transfer. I've deleted it. Please try again! 😄

**Comment by rborn** [comment]
You should have a request ❤️
