### ISSUE TITLE
Error while compiling angular.ts

### ISSUE THREAD

**Issue by mmyself** [rborn/nativescript-i18n#75]
Got an error while compiling the module, no glue why
Anybody else with this problem

ERROR in ../node_modules/nativescript-i18n/angular.ts
Module build failed (from ../node_modules/@ngtools/webpack/src/index.js):
Error: /Users/jan/Desktop/GrowTube/node_modules/nativescript-i18n/angular.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).

here is my enviroment.

✔ Getting NativeScript components versions information...
✔ Component nativescript has 6.2.0 version and is up to date.
⚠ Update available for component tns-core-modules. Your current version is 6.2.0 and the latest available version is 6.2.1.
✔ Component tns-android has 6.2.0 version and is up to date.
✔ Component tns-ios has 6.2.0 version and is up to date.

used it before, and never had a problem with it.

**Comment by agonper** [comment]
Same error here. Were you able to find a solution?

**Comment by xlmnxp** [comment]
easy way to use plugin in Angular:
app.module.ts
add next code after imports
```ts
import "nativescript-i18n";

@Pipe({
    name: 'L'
})
export class L implements PipeTransform {
    transform(value: string, ...more: string[]): string {
        return global["L"](value, ...more);
    }
}

@NgModule({
    declarations: [L],
    exports: [L]
})
export class NativeScriptI18nModule { }
```

then add `NativeScriptI18nModule` in `imports` inside `@NgModule`

```ts
@NgModule({
  bootstrap: [AppComponent],
  imports: [
    NativeScriptModule,
    AppRoutingModule,
    NativeScriptI18nModule
  ],
  declarations: [
    AppComponent,
  ],
  providers: [],
  schemas: [NO_ERRORS_SCHEMA]
})
export class AppModule {}
```

**Comment by agonper** [comment]
Thanks for the fast answer! Finally I decided to go with: https://github.com/EddyVerbruggen/nativescript-localize, since it worked out of the box. Thanks anyway.

**Comment by xlmnxp** [comment]
> Thanks for the fast answer! Finally I decided to go with: https://github.com/EddyVerbruggen/nativescript-localize, since it worked out of the box. Thanks anyway.

This means that my reply does not help you solve the issue :disappointed:

**Comment by isamilo** [comment]
Hello @xlmnxp still problem 'Error while compiling angular.ts'

**Comment by isamilo** [comment]
anyone can help please "ERROR in ../node_modules/nativescript-i18n/angular.ts
Module build failed (from ../node_modules/@ngtools/webpack/src/index.js):
Error: D:\Projects\masaa manne\BarPoint\node_modules\nativescript-i18n\angular.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property" 
I try to use localization in my Project,

**Comment by tscislo** [comment]
Even with suggestion mentioned by @xlmnxp this still does not work. Any chance for fixing this issue in the future?

**Comment by tscislo** [comment]
With @xlmnxp answer that works ok. Thank you!

**Comment by gabrielambriz75** [comment]
> easy way to use plugin in Angular:
> app.module.ts
> add next code after imports
> 
> ```ts
> import "nativescript-i18n";
> 
> @Pipe({
>     name: 'L'
> })
> export class L implements PipeTransform {
>     transform(value: string, ...more: string[]): string {
>         return global["L"](value, ...more);
>     }
> }
> 
> @NgModule({
>     declarations: [L],
>     exports: [L]
> })
> export class NativeScriptI18nModule { }
> ```
> 
> then add `NativeScriptI18nModule` in `imports` inside `@NgModule`
> 
> ```ts
> @NgModule({
>   bootstrap: [AppComponent],
>   imports: [
>     NativeScriptModule,
>     AppRoutingModule,
>     NativeScriptI18nModule
>   ],
>   declarations: [
>     AppComponent,
>   ],
>   providers: [],
>   schemas: [NO_ERRORS_SCHEMA]
> })
> export class AppModule {}
> ```

I use your reply and works for me, but when i try to use the plugin I got this issue, actually I still don't understand how to use it in angular, If you could mention what to put in each file would help me a lot.

![image](https://user-images.githubusercontent.com/33579971/120054617-95bd4000-bff6-11eb-9a60-cdfa83675498.png)
