### ISSUE TITLE
i18n folder (default and from customLangPath) has no effect, only the native resources are working

### ISSUE THREAD

**Issue by felixkrautschuk** [rborn/nativescript-i18n#76]
Environment:
- @nativescript/core 6.3.2
- nativescript-i18n 0.4.1
- issue occurs on both Android and iOS

According to the docs of this plugin, one should create an i18n folder in the app directory like this:
![Bildschirmfoto 2020-01-27 um 12 35 02](https://user-images.githubusercontent.com/6443021/73171657-8b88ea00-4101-11ea-8f18-ddf912a94c1c.png)

On my side, this folder has no effect, even when I'm defining a custom path for those resources and setting them in package.json, like it is done in the demo app, the language resources are not loaded. I'm not seeing any errors in the logs, but I also do not see the correct languages (only the keys like 'hello_world',...) on Android and iOS.

The only way to make languages working is defining them in the native App_Resources folders, so for Android:
<img width="251" alt="Bildschirmfoto 2020-01-27 um 12 38 44" src="https://user-images.githubusercontent.com/6443021/73171881-0a7e2280-4102-11ea-8490-7ba8532eeb03.png">

and for iOS:
<img width="203" alt="Bildschirmfoto 2020-01-27 um 12 39 47" src="https://user-images.githubusercontent.com/6443021/73171930-27b2f100-4102-11ea-8fe4-0d825570b5b3.png">

When I use the demo app of this repository, I can remove the app/resources/i18n folder and I get no error, as it seems that only the native language resources are used (on both Android and iOS).

Am I doing something completely wrong or are the docs not up-to-date?

**Comment by xlmnxp** [comment]
you should put `i18n` folder inside `app` folder **not** inside `app/resources`
did you change `appResourcesPath` in `nsconfig`?
plugin should use your custom paths

**Comment by Fr3nky88** [comment]
**[SOLVED]**
i have the same issue... 
this is my nsconfig.json
`{
  "appResourcesPath": "App_Resources",
  "appPath": "src"
}`

i put i18n dir in the app folder but it didn't work, then i put it like this: 
![immagine](https://user-images.githubusercontent.com/5224418/75804403-2cfa0000-5d80-11ea-9025-9f7fb89df7b8.png)
but also didn't work... 

what i'm wrong? 

Thanks...

SOLUTION: debuggin the pre-hook script in the plugin i find the solution, 
the plugin look the folder named "/app/i18n" by default, 
adding this in the pakage.json: 
`"nativescript-i18n": {
    "customLangPath": "src/i18n",
    "defaultLang": "it"
  }`
and putting the i18n folder in the "{rootProjectFolder}/src/i18n"
it work and generate the file correctly.
